estore/products/models.py
from estore import db
from datetime import datetime

#Create Tables for Brand and Category
class Categories(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False, unique=True)

class Brands(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(150), nullable=False, unique=True)

#Table for Product
class Product(db.Model):
    #Define Searchable property

    __searchable__ = ['name', 'desc']
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    price = db.Column(db.Numeric(10,2), nullable=False)
    discount = db.Column(db.Integer, nullable=False, default=0)
    stock = db.Column(db.Integer, nullable=False)
    pub_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow) 
    colors = db.Column(db.Text, nullable=False)
    descr = db.Column(db.Text, nullable=False)
    

    brand_id = db.Column(db.Integer, db.ForeignKey('brands.id'),nullable=False)
    brand = db.relationship('Brands', backref=db.backref('brands', lazy=True))

    category_id = db.Column(db.Integer, db.ForeignKey('categories.id'),nullable=False)
    category = db.relationship('Categories', backref=db.backref('categories', lazy=True))

    image_1 = db.Column(db.String(150), nullable=False, default='image.jpg')
    image_2 = db.Column(db.String(150), nullable=False, default='image.jpg')
    image_3 = db.Column(db.String(150), nullable=False, default='image.jpg')

    def __repr__(self):
        return f"Product('{self.name}', '{self.price}')"

estore/products/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DecimalField, IntegerField, TextAreaField, BooleanField
from flask_wtf.file import FileAllowed, FileField, FileRequired
from wtforms.validators import DataRequired, Length, NumberRange, InputRequired

class AddCategoryForm(FlaskForm):
    name = StringField('Category Name', validators=[DataRequired()])

class AddBrandForm(FlaskForm):
    name = StringField('Brand Name', validators=[DataRequired()])

#AddProduct Form
class AddProductForm(FlaskForm):
    name = StringField('Product Name', validators=[DataRequired()])
    price = DecimalField('Price', validators=[DataRequired(message="Invalid Input")])
    stock = IntegerField('Stock', validators=[NumberRange(min=0), InputRequired(message="Invalid Input")])
    discount = IntegerField('Discount', default=0)
    descr = TextAreaField('Description', validators=[DataRequired()])
    colors = TextAreaField('Colors', validators=[DataRequired()])

    image_1 = FileField('Image 1', validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'])])
    image_2 = FileField('Image 2', validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'])])
    image_3 = FileField('Image 3', validators=[FileAllowed(['jpg', 'jpeg', 'png', 'gif'])])

estore/products/routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from flask_login import login_required
from estore import db, photos
from estore.products.forms import AddCategoryForm, AddBrandForm, AddProductForm
from estore.products.models import Categories, Brands, Product
import secrets
import os

products = Blueprint('products', __name__)

#Route to add Category
@products.route('/add_category', methods=['GET','POST'])
def add_category():
    form = AddCategoryForm()
    if form.validate_on_submit():
        category = Categories(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash(f'The Category "{form.name.data}" has been added to the database.', 'success')
        return redirect(url_for('products.add_category'))
    return render_template('products/add_brand_or_cat.html', title='Add Category Page', form=form, categories='categories')

#Route to add Brand
@products.route('/add_brand', methods=['GET','POST'])
def add_brand():
    form = AddBrandForm()
    if form.validate_on_submit():
        brand = Brands(name=form.name.data)
        db.session.add(brand)
        db.session.commit()
        flash(f'The Brand "{form.name.data}" has been added to the database.', 'success')
        return redirect(url_for('products.add_brand'))
    return render_template('products/add_brand_or_cat.html', title='Add Brand Page', form=form, brands='brands')

@products.route('/add_product', methods=['GET', 'POST'])
@login_required
def add_product():
    brands = Brands.query.all()
    categories = Categories.query.all()
    form = AddProductForm()
    if form.validate_on_submit():

        name = form.name.data
        price = form.price.data
        discount = form.discount.data
        descr = form.descr.data
        stock = form.stock.data
        colors = form.colors.data
        brand = request.form.get('brand')
        category = request.form.get('category')

        #Hash photos before saving into directory
        image_1 = photos.save(request.files.get('image_1'), name=secrets.token_hex(16) + ".")
        image_2 = photos.save(request.files.get('image_2'), name=secrets.token_hex(16) + ".")
        image_3 = photos.save(request.files.get('image_3'), name=secrets.token_hex(16) + ".")

        #Add product details
        addpro = Product(name=name, price=price, discount=discount, colors=colors, descr=descr, 
            stock=stock, brand_id=brand, category_id=category, image_1=image_1, image_2=image_2, image_3=image_3)
        db.session.add(addpro)
        db.session.commit()
        flash(f"The product has been added to your database", 'success')
        return redirect(request.referrer)
    return render_template('products/add_product.html', title='Add Product Page', form=form, brands=brands, categories=categories)

#Route to view Products
@products.route('/view_products', methods=['GET', 'POST'])
@login_required
def view_products():
    products = Product.query.order_by(Product.id.desc()).all()
    return render_template('products/view_products.html', title='View Products Page', products=products)

#Route to view Brands
@products.route('/view_brands', methods=['GET', 'POST'])
@login_required
def view_brands():
    brands = Brands.query.order_by(Brands.id.desc()).all()
    return render_template('products/view_brand_or_cat.html', title='View Brands Page', brands=brands)

#Route to view Categories
@products.route('/view_categories', methods=['GET', 'POST'])
@login_required
def view_categories():
    categories = Categories.query.order_by(Categories.id.desc()).all()
    return render_template('products/view_brand_or_cat.html', title='View Categories Page', categories=categories)

#Route to Update Categories
@products.route('/update_category/<int:id>', methods=['GET', 'POST'])
@login_required
def update_category(id):
    
    form = AddCategoryForm()
    category = Categories.query.get_or_404(id)
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash(f'Category has been Updated!', 'success')
        return redirect(url_for('products.view_categories'))
    return render_template('products/update_brand_or_cat.html', title='Update Categories Page', category=category, form=form)

#Route to Update Brands
@products.route('/update_brand/<int:id>', methods=['GET', 'POST'])
@login_required
def update_brand(id):

    form = AddBrandForm()
    brand = Brands.query.get_or_404(id)
    if form.validate_on_submit():
        brand.name = form.name.data
        db.session.commit()
        flash(f'Brand has been Updated!', 'success')
        return redirect(url_for('products.view_brands'))
    return render_template('products/update_brand_or_cat.html', title='Update Brands Page', brand=brand, form=form)

#Route to update products
@products.route('/update_product/<int:id>', methods=['GET', 'POST'])
def update_product(id):
    form = AddProductForm()
    product = Product.query.get_or_404(id)

    #Update details on POST
    if form.validate_on_submit():
        product.name = form.name.data
        product.price = form.price.data
        product.discount = form.discount.data
        product.colors = form.colors.data
        product.stock = form.stock.data
        product.descr = form.descr.data
        product.brand_id = request.form.get('brand')
        product.category_id = request.form.get('category')

        #replace existing image with the new one in the image folder
        if request.files.get('image_1'):
            try:
                os.unlink(os.path.join(current_app.root_path, "static/products/images/" + product.image_1))
                product.image_1 = photos.save(request.files.get('image_1'), name=secrets.token_hex(16) + ".")
            except:
                product.image_1 = photos.save(request.files.get('image_1'), name=secrets.token_hex(16) + ".")

        if request.files.get('image_2'):
            try:
                os.unlink(os.path.join(current_app.root_path, "static/products/images/" + product.image_2))
                product.image_2 = photos.save(request.files.get('image_2'), name=secrets.token_hex(16) + ".")
            except:
                product.image_2 = photos.save(request.files.get('image_2'), name=secrets.token_hex(16) + ".")

        if request.files.get('image_3'):
            try:
                os.unlink(os.path.join(current_app.root_path, "static/products/images/" + product.image_3))
                product.image_3 = photos.save(request.files.get('image_3'), name=secrets.token_hex(16) + ".")
            except:
                product.image_3 = photos.save(request.files.get('image_3'), name=secrets.token_hex(16) + ".")

        
        db.session.commit()
        flash('Product has been Updated successfully', 'success')
        return redirect(url_for('products.view_products'))
    form.colors.data = product.colors
    form.descr.data = product.descr
    return render_template('products/update_product.html', title='Update Product Page', form=form, product=product)

#Route to delete categories 
@products.route('/delete_category/<int:id>/', methods=['POST'])
def delete_category(id):

    category = Categories.query.get_or_404(id)
    if request.method == 'POST':
        db.session.delete(category)
        db.session.commit()
        flash(f'The category "{category.name}" was deleted!', 'success')
        return redirect(url_for('products.view_categories'))

#Route to delete brands
@products.route('/delete_brand/<int:id>/', methods=['POST'])
def delete_brand(id):

    brand = Brands.query.get_or_404(id)
    if request.method == 'POST':
        db.session.delete(brand)
        db.session.commit()
        flash(f'The brand "{brand.name}" was deleted!', 'success')
        return redirect(url_for('products.view_brands'))

#Route to delete products
@products.route('/delete_product/<int:id>/', methods=['POST'])
def delete_product(id):

    product = Product.query.get_or_404(id)
    if request.method == 'POST':
        #Unlink Images from Images Folder
        try:
            os.unlink(os.path.join(current_app.root_path, "static/products/images/" + product.image_1))
            os.unlink(os.path.join(current_app.root_path, "static/products/images/" + product.image_2))
            os.unlink(os.path.join(current_app.root_path, "static/products/images/" + product.image_3))
        except Exception as e:
            print(e)
        db.session.delete(product)
        db.session.commit()
        flash(f'The product "{product.name}" was deleted!', 'success')
        return redirect(url_for('products.view_products'))
    else:
        flash("Can't delete Product", "danger")
        return redirect(url_for('products.view_products'))

estore/templates/products/add_brand_or_cat.html
{% extends "includes/prod_layout.html" %}
{% from "helpers/form_helper.html" import render_field %}
{% block content %}
<div class="page-inner">
    <div id="main-wrapper" style="margin-left: 14.8%;">
        <div class="col-md-8" style="margin-bottom: -2%;"> 
            {% include "helpers/messages.html" %}
        </div>
    </div>

    <div id="main-wrapper">
        <div class="row" style="margin-left: 15%;">
            {% if brands %}
            <div class="col-md-8">
                <div class="page-title">
                    <h3 class="breadcrumb-header"><b>Add Brand</b></h3>
                </div>
                <div class="panel-white">
                    <div class="panel-body">
                        <form method="POST" enctype="multipart/form-data">
                            {{ form.csrf_token }}
                            <div>
                                {{ render_field(form.name, class="form-control") }}
                            </div>
                            <br>
                            <div>
                                <input type="submit" value="Submit" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% elif categories %}
            <div class="col-md-8">
                <div class="page-title">
                    <h3 class="breadcrumb-header"><b>Add Category</b></h3>
                </div>
                <div class="panel-white">
                    <div class="panel-body">
                        <form method="POST" enctype="multipart/form-data">
                            {{ form.csrf_token }}
                            <div>
                                {{ render_field(form.name, class="form-control") }}
                            </div>
                            <br>
                            <div>
                                <input type="submit" value="Submit" class="btn btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}
        </div><!-- Row -->
    </div><!-- Main Wrapper -->
    <div class="page-footer">
        <p>Made with <i class="fa fa-heart"></i> by stacks</p>
    </div>
</div>
{% endblock content %}

estore/templates/products/view_brand_or_cat.html
{% extends "includes/prod_layout.html" %}
{% from "helpers/form_helper.html" import render_field %}
{% block content %}
<div class="page-inner">
    {% include "helpers/messages.html" %}
    <div class="page-title">
        {% if categories %}
        <h3 class="breadcrumb-header">Categories</h3>
        {% elif brands %}
        <h3 class="breadcrumb-header">Brands</h3>
        {% endif %}
    </div>
    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="panel-white">
                    <div class="panel-body">
                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-pills" role="tablist">
                                <li role="presentation"><a href="#">Home</a></li>
                                <li role="presentation"><a href="{{ url_for('products.view_products') }}">Products</a>
                                </li>
                                {% if brands %}
                                <li role="presentation" class="active"><a
                                        href="{{ url_for('products.view_brands') }}">Brands</a></li>
                                {% else %}
                                <li role="presentation"><a href="{{ url_for('products.view_brands') }}">Brands</a></li>
                                {% endif %}
                                {% if categories %}
                                <li role="presentation" class="active"><a
                                        href="{{ url_for('products.view_categories') }}">Categories</a></li>
                                {% else %}
                                <li role="presentation"><a
                                        href="{{ url_for('products.view_categories') }}">Categories</a></li>
                                {% endif %}
                                <li role="presentation"><a href="#">Tab 4</a></li>
                            </ul>
                            <!-- Product Table -->

                        </div>
                    </div>
                </div><br><br>
                <div class="panel-white">
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table id="example" class="display table" style="width: 100%;">
                                <thead>
                                    <tr>
                                        <th>SN</th>
                                        <th>Name</th>
                                        <th>Edit</th>
                                        <th>Delete</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% if brands %}
                                    {% for brand in brands %}
                                    <tr>
                                        <td>{{ loop.index }}</td>
                                        <td>{{ brand.name }}</td>
                                        <td>
                                            <a href="{{ url_for('products.update_brand', id = brand.id) }}"
                                                class="btn btn-primary btn-rounded">Update</a>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-danger btn-rounded" data-toggle="modal"
                                                data-target="#myModal-{{brand.id}}">Delete</button>
                                        </td>
                                    </tr>
                                    <div class="panel-white">
                                        <div class="panel-body">
                                            <div class="modal fade" id="myModal-{{ brand.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                                <div class="modal-dialog" role="document">
                                                  <div class="modal-content">
                                                    <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                      <h4 class="modal-title" id="myModalLabel">{{ brand.name }}</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                      <span class="text-danger" style="font-size: 15px;">
                                                          Are you sure you want to delete this brand &nbsp;"{{ brand.name }}"?
                                                      </span>
                                                    </div>
                                                    <div class="modal-footer">
                                                      <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;&nbsp;
                                                      <form method="POST" action="{{ url_for('products.delete_brand', id=brand.id) }}" style="display: inline;">
                                                      <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                        </div>
                                    </div>
                                    {% endfor %}

                                    {% elif categories %}
                                    {% for category in categories %}
                                    <tr>
                                        <td>{{ loop.index }}</td>
                                        <td>{{ category.name }}</td>
                                        <td>
                                            <a href="{{ url_for('products.update_category', id = category.id) }}"
                                                class="btn btn-primary btn-rounded">Update</a>
                                        </td>
                                        <td>
                                            <button type="button" class="btn btn-danger btn-rounded" data-toggle="modal"
                                                data-target="#myModal-{{category.id}}">Delete</button>
                                        </td>
                                    </tr>
                                    <div class="panel-white">
                                        <div class="panel-body">
                                            <div class="modal fade" id="myModal-{{ category.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                                <div class="modal-dialog" role="document">
                                                  <div class="modal-content">
                                                    <div class="modal-header">
                                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                      <h4 class="modal-title" id="myModalLabel">{{ category.name }}</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                      <span class="text-danger" style="font-size: 15px;">
                                                          Are you sure you want to delete this category &nbsp;"{{ category.name }}"?
                                                      </span>
                                                    </div>
                                                    <div class="modal-footer">
                                                      <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;&nbsp;
                                                      <form method="POST" action="{{ url_for('products.delete_category', id=category.id) }}" style="display: inline;">
                                                      <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                    {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- Row -->
    </div><!-- Main Wrapper -->
    <div class="page-footer">
        <p>Made with <i class="fa fa-heart"></i> by stacks</p>
    </div>
</div>
{% endblock content %}

estore/templates/products/view_products.html
{% extends "includes/prod_layout.html" %}
{% from "helpers/form_helper.html" import render_field %}
{% block content %}
<div class="page-inner">
    {% include "helpers/messages.html" %}
    <div class="page-title">
        <h3 class="breadcrumb-header">Products</h3>
    </div>
    <div id="main-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="panel-white">
                    <div class="panel-body">
                        <div role="tabpanel">
                            <!-- Nav tabs -->
                            <ul class="nav nav-pills" role="tablist">
                                <li role="presentation"><a href="#">Home</a></li>
                                <li role="presentation" class="active"><a href="{{ url_for('products.view_products') }}">Products</a></li>
                                <li role="presentation"><a href="{{ url_for('products.view_brands') }}">Brands</a></li>
                                <li role="presentation"><a href="{{ url_for('products.view_categories') }}">Categories</a></li>
                                <li role="presentation"><a href="#">Tab 4</a></li>
                            </ul>
                            <!-- Product Table -->
                            
                        </div>
                    </div>
                </div><br><br>
                <div class="panel-white">
                    <div class="panel-body">
                       <div class="table-responsive">
                        <table id="example" class="display table" style="width: 100%;">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Image</th>
                                    <th>Product</th>
                                    <th>Brand</th>
                                    <th>Price</th>
                                    <th>Discount</th>
                                    <th>Edit</th>
                                    <th>Delete</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for product in products %}
                                <tr>
                                    <td>{{ loop.index }}</td>
                                    <td>
                                        <img src="{{ url_for('static', filename='products/images/' + product.image_1) }}" 
                                            alt="product_img.jpg" width="45" height="50">
                                    </td>
                                    <td>{{ product.name }}</td>
                                    <td>{{ product.brand.name }}</td>
                                    <td>{{ product.price }}</td>
                                    <td>{{ product.discount }}</td>
                                    <td>
                                        <a href="{{ url_for('products.update_product', id=product.id) }}" class="btn btn-primary btn-rounded">Update</a>
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-danger btn-rounded" data-toggle="modal"
                                                data-target="#myModal-{{product.id}}">Delete</button>
                                    </td>
                                </tr>
                                <div class="panel-white">
                                    <div class="panel-body">
                                        <div class="modal fade" id="myModal-{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                                            <div class="modal-dialog" role="document">
                                              <div class="modal-content">
                                                <div class="modal-header">
                                                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                  <h4 class="modal-title" id="myModalLabel">{{ product.name }}</h4>
                                                </div>
                                                <div class="modal-body">
                                                  <span class="text-danger" style="font-size: 15px;">
                                                      Are you sure you want to delete this product &nbsp;"{{ product.name }}"?
                                                  </span>
                                                </div>
                                                <div class="modal-footer">
                                                  <button type="button" class="btn btn-warning" data-dismiss="modal">Cancel</button>&nbsp;&nbsp;&nbsp;
                                                  <form method="POST" action="{{ url_for('products.delete_product', id=product.id) }}" style="display: inline;">
                                                  <button type="submit" class="btn btn-danger">Delete</button>
                                                </form>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </tbody>
                           </table>  
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- Row -->
    </div><!-- Main Wrapper -->
    <div class="page-footer">
        <p>Made with <i class="fa fa-heart"></i> by stacks</p>
    </div>
</div>
{% endblock content %}