estore/users/models.py
from estore import db
from datetime import datetime
import json



class Customer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)  
    username = db.Column(db.String(50), nullable=False, unique=True)
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(150), nullable=False)

    def __repr__(self):
        return f"Customer('{self.username}', '{self.email}')"

class Address(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), nullable=False)
    last_name = db.Column(db.String(50), nullable=False)
    company = db.Column(db.String(50), nullable=False)
    country = db.Column(db.String(50), nullable=False)
    street_add = db.Column(db.String(50), nullable=False)
    city = db.Column(db.String(50), nullable=False)
    postcode = db.Column(db.String(50), nullable=False)
    mobile_no = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    date_created= db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    customer_id = db.Column(db.Integer, db.ForeignKey('customer.id'), nullable=False)
    ccustomer = db.relationship('Customer', backref=db.backref('customer', lazy=True))

    def __repr__(self):
        return f"Address('{self.email}', '{self.mobile_no}', '{self.first_name}', '{self.last_name}')"

#define class to dump orders into database
class JsonEncodedDict(db.TypeDecorator):
    impl = db.Text

    def process_bind_param(self, value, dialect):
        #If there are no items
        if value is None:
            return '{}'
        else:
            return json.dumps(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return '{}'
        else:
            return json.loads(value)



#Create table for customer orders
class CustomerOrder(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    invoice = db.Column(db.String(50), nullable=False, unique=True)
    status = db.Column(db.String(50), nullable=False, default='Pending')
    customer_id = db.Column(db.String(50), unique=False, nullable=False)
    date_created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    orders = db.Column(JsonEncodedDict)

    def __repr__(self):
        return f"CustomerOrder('{self.invoice}', '{self.customer_id}')"

estore/users/routes.py
from flask import render_template, redirect, url_for, session, Blueprint, request, flash, make_response
from estore import db, bcrypt
from flask_login import  current_user
from estore.users.models import Customer, CustomerOrder, Address
import secrets
import pdfkit

users = Blueprint('users', __name__)

@users.route('/customer_registration', methods=['GET', 'POST'])
def customer_registration():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    #Get form details from template
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')

    #hash password before storing into database
    if request.method == 'POST':
        hashed_pw = bcrypt.generate_password_hash(password)
        #Query to see if user details is not in database
        customer = Customer.query.filter_by(email=email).first()
        if customer:
            flash(f'Email already exists!', 'danger')
            return redirect(url_for('users.customer_registration'))
        else:
            user = Customer(first_name=first_name, last_name=last_name, username=username, email=email, password=hashed_pw)
            db.session.add(user)
            db.session.commit()
            flash(f'Account created successfully!', 'success')
            return redirect(url_for('users.customer_registration'))
    return render_template('users/user_login_reg_form.html', title='Account Page', registration='registration')

@users.route('/customer_login', methods=['GET','POST'])
def customer_login():

    if 'customer' in session:
        return redirect(url_for('main.home'))

    email = request.form.get('email')
    password= request.form.get('password')
    remember = request.form.get('rememberCheckbox')

    
    if request.method == 'POST':
        user = Customer.query.filter_by(email=email).first() 
        if user and bcrypt.check_password_hash(user.password, password):
            session['customer'] = email
            flash(f'Login successful', 'success')
            return redirect(url_for('main.home'))
        #Check password hash and user if they exist
        else:
            flash(f'Incorrect username/password!. Please try again', 'danger')
            return redirect(url_for('users.customer_login'))
    return render_template('users/user_login_reg_form.html', title='Account Page', login='login')

@users.route('/customer_logout')
def customer_logout():
    try:
        session.pop('customer', None)
        return redirect(url_for('main.home'))
    except Exception as e:
        print(e)
        return redirect(url_for('main.home'))

@users.route('/checkout', methods=['GET', 'POST'])
def checkout():

    #Check to see if there are items in the shopping cart
    sub_total = 0
    vat = 0
    grand_total = 0
    shipping_fee = 125
    
    if 'Shoppingcart' not in session or len(session['Shoppingcart']) <=0:
        return redirect(url_for('main.home'))
    #If items are there, calculate grandtotal of items
    for key, product in session['Shoppingcart'].items():
        discount_price = product['price']-((product['discount']/100) * (product['price']))
        sub_total += (float(product['quantity']) * discount_price)
        vat += (0.05 * float(product['quantity']) * product['price'])
        grand_total = sub_total + vat + shipping_fee

    if request.method == 'POST':
        first_name = request.form.get('firstName')
        last_name = request.form.get('lastName')
        company = request.form.get('companyName')
        country = request.form.get('country')
        street_add = request.form.get('streetAddress')
        city = request.form.get('cityAddress')
        postcode = request.form.get('postcode')
        email = request.form.get('emailAddress')
        mobile_no = request.form.get('mobileno')
        #Get id of customer if User is logged in
        if 'customer' in session:
            customer = Customer.query.filter_by(email=session['customer']).first()
            customer_id = customer.id
        else:
            customer_id = int(0)
        #Get order details
        invoice = secrets.token_hex(16)
        try:
            #Put orders into database
            order = CustomerOrder(invoice=invoice, customer_id=customer_id, orders=session['Shoppingcart'])
            #Store Address of Customer
            cust_details = Address(first_name=first_name, last_name=last_name, company=company, country=country, street_add=street_add,
                                city=city, postcode=postcode, mobile_no=mobile_no, email=email, customer_id=customer_id)
            db.session.add(cust_details)
            db.session.add(order)
            db.session.commit()
            #Clear carts in session
            session.pop('Shoppingcart')
            flash(f'Your order has been sent successfully!', 'success')
            return redirect(url_for('users.view_orders', invoice=invoice))
        except Exception as e:
            flash('Something went wrong while getting order', 'danger')
            print(e)
            return redirect(url_for('users.checkout'))

    return render_template('users/checkout.html', title='CheckOut Page', vat=vat, 
                            grand_total=grand_total, sub_total=sub_total, shipping_fee=shipping_fee)



@users.route('/view_orders/<invoice>')
def view_orders(invoice):

    if 'customer' in session:
        sub_total = 0
        vat = 0
        grand_total = 0
        shipping_fee = 125
        cust = Customer.query.filter_by(email=session['customer']).first()
        customer_id = cust.id
        customer = Customer.query.filter_by(id=customer_id).first()
        #Get the latest order from customer
        orders = CustomerOrder.query.filter_by(customer_id=customer_id).order_by(CustomerOrder.id.desc()).first()
        address = Address.query.filter_by(customer_id=customer_id).order_by(Address.id.desc()).first()

        for key, product in orders.orders.items():
            discount_price = product['price']-((product['discount']/100) * (product['price']))
            sub_total += (float(product['quantity']) * discount_price)
            vat += (0.05 * float(product['quantity']) * product['price'])
            grand_total = sub_total + vat + shipping_fee
    else:
        return redirect(url_for('main.home'))    

    return render_template('users/new_.html', title='Orders Page', customer=customer, orders=orders,
                    sub_total=sub_total, grand_total=grand_total, vat=vat, shipping_fee=shipping_fee, address=address)

@users.route('/get_pdf/<invoice>', methods=['POST'])
def get_pdf(invoice):

    if 'customer' in session:
        sub_total = 0
        vat = 0
        grand_total = 0
        shipping_fee = 125
        if request.method == 'POST':
            cust = Customer.query.filter_by(email=session['customer']).first()
            customer_id = cust.id
            customer = Customer.query.filter_by(id=customer_id).first()
            #Get the latest order from customer
            orders = CustomerOrder.query.filter_by(customer_id=customer_id).order_by(CustomerOrder.id.desc()).first()
            address = Address.query.filter_by(customer_id=customer_id).first()

            for key, product in orders.orders.items():
                discount_price = product['price']-((product['discount']/100) * (product['price']))
                sub_total += (float(product['quantity']) * discount_price)
                vat += (0.05 * float(product['quantity']) * product['price'])
                grand_total = sub_total + vat + shipping_fee   

            rendered =  render_template('users/get_orders_pdf.html', title='Orders Page', customer=customer, orders=orders,
                            sub_total=sub_total, grand_total=grand_total, vat=vat, shipping_fee=shipping_fee, address=address)
            
            #Get pdf
            pdf = pdfkit.from_string(rendered, False)
            response = make_response(pdf)
            response.headers['content-Type'] = 'application/pdf'
            response.headers['content-Dispostion'] = 'inline: filename='+ invoice +'.pdf'
            return response

    return redirect(url_for('users.view_orders'))

@users.route('/view')
def view_pdf():
    return render_template('users/invoice.html')

estore/templates/users/get_orders_pdf.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Title -->
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Eshop Page</title>
    {% endif %}


    <!-- Required Meta Tags Always Come First -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Google Fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&display=swap"
        rel="stylesheet">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.1/css/all.min.css">
    
    <!-- CSS Electro Template -->
    <link rel="stylesheet" href="https://transvelo.github.io/electro-html/2.0/assets/css/theme.css">
</head>


<body>
    <!-- ========== MAIN CONTENT ========== -->
<main id="content" role="main" class="checkout-page">
    <!-- breadcrumb -->
    <div class="bg-gray-13 bg-md-transparent">
        <div class="container">
            <!-- breadcrumb --> 
            <div class="my-md-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-3 flex-nowrap flex-xl-wrap overflow-auto overflow-xl-visble">
                        
                    </ol>
                </nav>
            </div>
            <!-- End breadcrumb -->
        </div>
    </div>
    <!-- End breadcrumb -->

    <div class="container mt-3">
        <div class="mb-5">
            <h1 class="text-center">Order Details</h1>
        </div>        
            <div class="row">
                <div class="col-md-12 mb-12">
                    <div class="">
                        <div class="">
                                <div style="display: inline-flex;">
                                    <div class="col-md-12" style="padding-left:0;">
                                        <h3 class="m-b-md m-t-xxs"><b>Santana Electronics</b></h3>
                                        <address>
                                            Kumasi-Adum, Ghana<br>
                                            Phone: +(233) 57-890-8164
                                        </address>
                                    </div>
                                    <div class="col-md-12 text-right" style="position: absolute; margin-left: -15px;">
                                        <h4 class="" style="margin-right: 20px;"><strong>Invoice:</strong>
                                            <span style="font-size: 15px;">{{ orders.invoice }}</span></h4>
                                        
                                        
                                        
                                    </div>
                                </div>
                                <div class="col-md-12" style="padding-left:0;">
                                    <hr>
                                    <p>
                                        <strong>Invoice to</strong><br>
                                        {{ address.first_name }}&nbsp;{{ address.last_name }}<br>
                                        {{ address.street_add }}<br>
                                        {{ address.city }}, {{ address.postcode }} <br>
                                        {{ address.country }}
                                    </p>
                                </div>
                                <div class="col-md-12 mb-6 cart-table" style="padding-left:0;padding-right:0;">
                                    <table class="table" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th class="product-no">SN</th>
                                                <th class="product-name">Product</th>
                                                <th class="product-color">Color</th>
                                                <th class="product-price">Price</th>
                                                <th class="product-quantity w-lg-15">Quantity</th>
                                                <th class="product-subtotal">Total</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for key, item in orders.orders.items() %} 
                                            <tr class="">
                                                <td data-title="Number">
                                                    <a href="#" class="text-gray-90">{{ loop.index }}</a>
                                                </td>

                                                <td data-title="Product">
                                                    <a href="#" class="text-gray-90">{{ item.name }}</a>
                                                </td>

                                                <td data-title="Color">
                                                    <a href="#" class="text-gray-90">{{ item.color }}</a>
                                                </td>
            
                                                <td data-title="Price">
                                                    <span class="">${{ item.price }}</span>
                                                </td>

                                                <td data-title="Quantity">
                                                    <span class="">{{ item.quantity }}</span>
                                                </td>
            
                                                <td data-title="Total">
                                                    {% set dis = "%.2f"|format(((100-item.discount)/100)) %}
                                                    <span class="">
                                                        ${{ "%.2f"|format(dis|float*(item.price)*(item.quantity|float)) }}
                                                    </span>
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                                <hr>
                                <br>
                                <div class="mb-12" style="display: inline-flex;">
                                    <div class="row">
                                        <div class="col-md-12" style="padding-left:0;">
                                        <h4>Thank you!</h4>
                                        <p>nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula.</p>
                                        <img src="http://via.placeholder.com/350x150?text=signature" height="150" class="m-t-lg" alt="">
                                    </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-8" style="position: absolute;">
                                            <div class="text-right" >
                                                <h5>Subtotal</h5>
                                                <span class="font-size-16">${{ "%.2f"|format(sub_total) }}</span>
                                                <hr>
                                                <h5>Shipping</h5>
                                                <span class="font-size-16">Flat rate ${{ "%.2f"|format(shipping_fee) }}</span>
                                                <hr>
                                                <h5>VAT</h5>
                                                <span class="font-size-16">${{ "%.2f"|format(vat) }}</span>
                                                <hr>
                                                <h4 class="text-success"><strong>Total</strong></h4>
                                                <span class="text-success font-size-18"><strong>${{ "%.2f"|format(grand_total) }}</strong></span>
                                                <hr>  
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                
                        </div>
                    </div>
                </div>
            </div>
        
    </div>
</main>
</body>
</html>

estore/templates/users/view_orders.html
{% extends "includes/pages_layout.html" %}
{% block content %}
<!-- ========== MAIN CONTENT ========== -->
<main id="content" role="main" class="checkout-page">
    <!-- breadcrumb -->
    <div class="bg-gray-13 bg-md-transparent">
        <div class="container">
            {% include "helpers/messages.html" %}
            <!-- breadcrumb -->
            <div class="my-md-3">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb mb-3 flex-nowrap flex-xl-wrap overflow-auto overflow-xl-visble">
                        <li class="breadcrumb-item flex-shrink-0 flex-xl-shrink-1"><a href="../home/index.html">Home</a>
                        </li>
                        <li class="breadcrumb-item flex-shrink-0 flex-xl-shrink-1 active" aria-current="page">Checkout
                        </li>
                    </ol>
                </nav>
            </div>
            <!-- End breadcrumb -->
        </div>
    </div>
    <!-- End breadcrumb -->

    <div class="container">
        <div class="mb-5">
            <h1 class="text-center">Order Details</h1>
        </div>
        <div class="row">
            <div class="col-md-12 mb-12">
                <div class="">
                    <div class="">
                        <div style="display: inline-flex;">
                            <div class="col-md-12" style="padding-left:0;">
                                <h3 class="m-b-md m-t-xxs"><b>Santana Electronics</b></h3>
                                <address>
                                    Kumasi-Adum, Ghana<br>
                                    Phone: +(233) 57-890-8164
                                </address>
                            </div>
                            <div class="col-md-12 text-right" style="position: absolute; margin-left: -55px;">
                                <h3 class="" style="margin-right: 20px;">Invoice</h3>

                                <form action="{{ url_for('users.get_pdf', invoice=orders.invoice) }}" method="POST">
                                    <button type="submit" class="btn btn btn-primary-dark-w">
                                        <i class="fa fa-print"></i> Get Invoice
                                    </button>
                                </form>
                            </div>
                        </div>
                        <div class="col-md-12" style="padding-left:0;">
                            <hr>
                            <p>
                                <strong>Invoice to</strong><br>
                                {{ address.first_name }}&nbsp;{{ address.last_name }}<br>
                                {{ address.street_add }}<br>
                                {{ address.city }}, {{ address.postcode }} <br>
                                {{ address.country }}
                            </p>
                        </div>
                        <div class="col-md-12 mb-6 cart-table" style="padding-left:0;padding-right:0;">
                            <table class="table" cellspacing="0">
                                <thead>
                                    <tr>
                                        <th>S/N</th>
                                        <th>Product</th>
                                        <th>Color</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for key, item in orders.orders.items() %}
                                    <tr class="">
                                        <td data-title="Number">
                                            <a href="#" class="text-gray-90">{{ loop.index }}</a>
                                        </td>

                                        <td data-title="Product">
                                            <a href="#" class="text-gray-90">{{ item.name }}</a>
                                        </td>

                                        <td data-title="Color">
                                            <a href="#" class="text-gray-90">{{ item.color }}</a>
                                        </td>

                                        <td data-title="Price">
                                            <span class="">${{ item.price }}</span>
                                        </td>

                                        <td data-title="Quantity">
                                            <span class="">{{ item.quantity }}</span>
                                        </td>

                                        <td data-title="Total">
                                            {% set dis = "%.2f"|format(((100-item.discount)/100)) %}
                                            <span class="">
                                                ${{ "%.2f"|format(dis|float*(item.price)*(item.quantity|float)) }}
                                            </span>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <hr>
                        <br>
                        <div class="mb-12" style="display: inline-flex;">
                            <div class="row">
                                <div class="col-md-12" style="padding-left:0;">
                                    <h4>Thank you!</h4>
                                    <p>nascetur ridiculus mus. Nullam id dolor id nibh ultricies vehicula.</p>
                                    <img src="http://via.placeholder.com/350x150?text=signature" height="150"
                                        class="m-t-lg" alt="">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-8" style="position: absolute;">
                                    <div class="text-right">
                                        <h5>Subtotal</h5>
                                        <span class="font-size-16">${{ "%.2f"|format(sub_total) }}</span>
                                        <hr>
                                        <h5>Shipping</h5>
                                        <span class="font-size-16">Flat rate ${{ "%.2f"|format(shipping_fee) }}</span>
                                        <hr>
                                        <h5>VAT</h5>
                                        <span class="font-size-16">${{ "%.2f"|format(vat) }}</span>
                                        <hr>
                                        <h4 class="text-success"><strong>Total</strong></h4>
                                        <span class="text-success font-size-18"><strong>${{ "%.2f"|format(grand_total)
                                                }}</strong></span>
                                        <hr>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</main>
<!-- ========== END MAIN CONTENT ========== -->
{% endblock content %}